project_id = "neue-local"

[api]
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322

[studio]
port = 54323

[auth]
site_url = "http://localhost:3002"
additional_redirect_urls = [
  "http://localhost:3000/*",
  "http://localhost:3001/*",
  "http://localhost:3002/*"
]
